PhoneBookWeb/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBookApp.Logic.Models;
using PhoneBookApp.Logic.Services.Users;
using System;

namespace PhoneBookApp.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult FAQ()
        {
            if (_userService.SignedIn)
            {
                return FAQLogged();
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult FAQLogged()
        {
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            if (_userService.SignedIn)
            {

            }

            return View();
        }

        [HttpPost]
        public IActionResult SignIn(Credentials credentials)
        {
            if (ModelState.IsValid)
            {
                bool signInSuccess = _userService.SignIn(credentials);

                if (signInSuccess)
                {
                    return Redirect("../User/PersonalData");
                }
                else
                {
                    ViewBag.ErrorMessage = "Incorrect credentials.";
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(NewUser newUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _userService.SignUp(newUser);

                    return Redirect("../User/PersonalData");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult MainPage()
        {
            if (_userService.SignedIn)
            {
                return MainPageLogged();
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult MainPageLogged()
        {
            return View();
        }

        [HttpGet]
        public IActionResult LogOut()
        {
            _userService.LogOut();
            return Redirect("../Login/SignIn");
        }
    }
}

PhoneBookWeb/Controllers/PhoneBookController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBookApp.Data.Entities;
using PhoneBookApp.Logic.Models;
using PhoneBookApp.Logic.Services.PhoneBooks;
using PhoneBookApp.Logic.Services.Users;
using System;
using System.Collections.Generic;

namespace PhoneBookApp.Controllers
{
    // IActionResult to interfejs (albo "kontrakt") dla wszystkiego co może zostać zwrócone do przeglądarki internetowej (albo po prostu dla żądania)
    public class PhoneBookController : Controller
    {
        // Zadanko domowe:
        // Podorabiać serwisy, z jakąś logiką, np walidacyjną (na jakieś błędne dane throw new Exception z odpowiednim komunikatem, a tu w kontrolerze try catch)
        // Pododawać dane testowe, żeby było na czym pracować

        private readonly IPhoneBookService _phoneBookService;
        private readonly IUserService _userService;

        public PhoneBookController(IPhoneBookService phoneBookService, IUserService userService)
        {
            _phoneBookService = phoneBookService;
            _userService = userService;
        }

        [HttpGet]
        [ResponseCache(NoStore = true)]
        public IActionResult ShowAllPhoneBooks()
        {
            if (_userService.SignedIn)
            {
                // Tu wszelki testowy kod !

                List<PhoneBook> phoneBooks = _phoneBookService.GetAllPhoneBooks(_userService.SignedInUser);

                // Metoda View() będzie szukała widoku w lokacji Views/PhoneBook/Index.cshtml
                // A bierze się to ze "wzoru"                    Views/NazwaKontrolera/NazwaAkcji.cshtml
                return View(phoneBooks); 
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true)]
        public IActionResult CreatePhoneBook()
        {
            if (_userService.SignedIn)
            {
                return View();
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpPost]
        [ResponseCache(NoStore = true)]
        public IActionResult CreatePhoneBook(PhoneBook phoneBook)
        {
            if (_userService.SignedIn)
            {
                try
                {
                    _phoneBookService.CreatePhoneBook(_userService.SignedInUser, phoneBook);
                    return Redirect("../PhoneBook/ShowAllPhoneBooks ");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    return View();
                }
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpPost]
        [ResponseCache(NoStore = true)]
        public IActionResult EditPhoneBook(PhoneBook phoneBook)
        {
            if (_userService.SignedIn)
            {
                return View();
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true)]
        public IActionResult DeletePhoneBook(int phoneBookId)
        {
            if (_userService.SignedIn)
            {
                _phoneBookService.DeletePhoneBookById(phoneBookId);

                return Redirect("../PhoneBook/ShowAllPhoneBooks");
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true)]
        public IActionResult ShowContacts(int phoneBookId)
        {
            if (_userService.SignedIn)
            {
                PhoneBook phoneBook = _phoneBookService.GetPhoneBookById(phoneBookId);

                return View(phoneBook);
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true)]
        public IActionResult CreateContact(int phoneBookId)
        {
            if (_userService.SignedIn)
            {
                PhoneBook phoneBook = _phoneBookService.GetPhoneBookById(phoneBookId);

                ViewBag.PhoneBookId = phoneBook.Id;

                return View();
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpPost]
        [ResponseCache(NoStore = true)]
        public IActionResult CreateContact(NewContact newContact)
        {
            if (_userService.SignedIn)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _phoneBookService.AddContact(newContact);
                        return Redirect($"../PhoneBook/ShowContacts?phoneBookId={newContact.PhoneBookId}");
                    }
                    catch (Exception e)
                    {
                        ViewBag.ErrorMessage = e.Message;
                        ViewBag.PhoneBookId = newContact.PhoneBookId;
                        return View();
                    }
                }
                else
                {
                    ViewBag.PhoneBookId = newContact.PhoneBookId;
                    return View();
                }
            }
            else
            {
                return View("NoAccess");
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true)]
        public IActionResult DeleteContact(int phoneBookId, int contactId)
        {
            if (_userService.SignedIn)
            {
                _phoneBookService.DeleteContactById(phoneBookId, contactId);

                return Redirect($"../PhoneBook/ShowContacts?phoneBookId={phoneBookId}");
            }
            else
            {
                return View("NoAccess");
            }
        }
    }
}

PhoneBookWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBookApp.Data.Entities;
using PhoneBookApp.Logic.Models;
using PhoneBookApp.Logic.Services.TimeZoneApi;
using PhoneBookApp.Logic.Services.Users;

namespace PhoneBookApp.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITimeZoneApiService _timeZoneApiService;

        public UserController(IUserService userService, ITimeZoneApiService timeZoneApiService)
        {
            _userService = userService;
            _timeZoneApiService = timeZoneApiService;
        }

        [HttpGet]
        public IActionResult PersonalData()
        {
            if (_userService.SignedIn)
            {
                ViewBag.Premium = "Premium user";
                ViewBag.Standard = "Standard user";

                TimeZoneApiResult timeZoneApiResult = _timeZoneApiService.GetTimeZone("Europe", "Warsaw");

                PersonalDataPack personalDataPack = new PersonalDataPack
                {
                    User = _userService.SignedInUser,
                    TimeZoneApiResult = timeZoneApiResult
                };

                return View(personalDataPack);
            }
            else
            {
                // TODO: Utworzyć widok braku dostępu
                return View("NoAccess");
            }
        }

        //[HttpPost]
        //public IActionResult PersonalData(PersonalData personalData)
        //{
        //    return Ok();
        //}

        [HttpGet]
        public IActionResult PersonalDataEdition()
        {
            if (_userService.SignedIn)
            {
                PersonalDataEdition personalDataEdition = new PersonalDataEdition
                {
                    Name = _userService.SignedInUser.PersonalData.Name,
                    Surname = _userService.SignedInUser.PersonalData.Surname,
                    Age = _userService.SignedInUser.PersonalData.Age,
                    EmailAddress = _userService.SignedInUser.PersonalData.EmailAddress,
                };

                // TODO: przekazać model personal data i uzupełnić kontrolki danymi personalnymi usera
                return View(personalDataEdition);
            }
            else
            {
                // TODO: Utworzyć widok braku dostępu
                return View("NoAccess");
            }

        }

        [HttpPost]
        public IActionResult PersonalDataEdition(PersonalDataEdition personalDataEdition)
        {
            if (ModelState.IsValid)
            {
                _userService.PersonalDataEdition(personalDataEdition);
                return Redirect("../User/PersonalData");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePassword changePassword)
        {
            if (ModelState.IsValid)
            {
                _userService.ChangePassword(changePassword);
                return Redirect("../User/PersonalData");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult UpgradeUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UpgradeUser(PremiumCode premiumCode)
        {
            if (ModelState.IsValid)
            {
                _userService.UpgradeUser(premiumCode);
                return Redirect("../User/PersonalData");
            }
            else
            {
                return View();
            }
        }
    }
}

PhoneBookWeb/Views/Shared/Logged.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBookApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" >PhoneBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="MainPageLogged">Main Page</a>
                        </li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="FAQLogged">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="PersonalData">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PhoneBook" asp-action="ShowAllPhoneBooks">Phonebooks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PhoneBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PhoneBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBookApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" >PhoneBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="MainPage">Main Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="FAQ">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="SignIn">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="SignUp">Sign Up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PhoneBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>